# backend/Dockerfile.prod
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .

# Production bosqichi
FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app ./

ENV NODE_ENV=production
ENV PORT=5000

# Non-root user
USER node

EXPOSE 5000
CMD ["npm", "start"]
